# Generated by Django 5.0.1 on 2024-04-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('department', models.CharField(max_length=20, verbose_name='Department')),
                ('date', models.CharField(max_length=50, verbose_name='Date')),
                ('message', models.CharField(max_length=100, verbose_name='Message')),
            ],
        ),
    ]
