# Generated by Django 5.0.1 on 2024-04-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic_app', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('degree', models.CharField(max_length=20)),
                ('photo', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
